[tools]
go = "1.25.6"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/air-verse/air" = "latest"

[tasks.docs]
description = "Preview documentation"
run = "mise run -C docs preview"

[tasks.server]
description = "Build and start the server"
run = "mise run -C server start"
